name: Playwright Tests

on: [push, pull_request]

permissions: write-all

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16' # Ensure you use a compatible Node.js version

      - name: Install dependencies
        run: npm install

      - name: Install Playwright Browsers
        run: npx playwright install

      - name: Run Playwright tests
        run: npm test

      - name: Upload Playwright report
        if: always()
        run: |
          timestamp=$(date +%Ym%d%H%M%S)
          new_dir="playwright-report-$timestamp"
          mv playwright-report $new_dir
          echo "new_dir=$newdir" >> $GITHUB_ENV
        # uses: actions/upload-artifact@v2
        # with:
        #   name: playwright-report
        #   path: playwright-report

      - name: Setup Pages
        uses: actions/configure-pages@v2

      - name: Upload Artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: playwright-report

      - name: Deploy Playwright report to Github Pages
        id: deployment
        uses: actions/deploy-pages@v1
